# конфиг для smb-mount.sh
# если не указан user или pass то будет попытка смонтировать nobody
# если не указан path то path будет
# использован base_path/<ip>/<folder_share>
# где вместо ip будет либо hostname либо последние два числа из ip адреса
# аварийная команда размонтирования
# sudo umount -t cifs -a -l
#########################################

# Здесь разрешено использовать только полный путь от корня!
base_path=/home/user

# Ниже ваши ресурсы для монтирования:
# каждый блок должен содержать 4 строки
# ip - ip адрес или hostname
# user -имя пользователя
# pass -пароль
# path -полный путь куда монтировать начиная от корня!
ip=192.168.3.2
user=user
pass=123
path=
# каждый такой блок должен быть разделён пробелом или комментарием
ip=192.168.3.4
user=user
pass=123
path=

ip=192.168.3.6
user=user
pass=123
path=
